# config.yml
# support environment variables in .env file

# change PMS path here (not used anymore)
# path before /Library/Application Support/Metadata
# !!!!!!! DO NOT OMMIT THE LAST SLASH "/" !!!!!!!
# plex_root: '/docker/plex/Library/Application Support/Plex Media Server/'

# change plex url and token here
# !!!!!!! OMMIT THE LAST SLASH "/" !!!!!!!!
baseurl: ${PLEX_URL} # i.e http://192.168.1.1:32400 or if reverse proxied i.e. https://plex.yourtld.com
token: ${PLEX_TOKEN} # how to get token https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

# input the libraries you want to export NFO/poster/fanart from
library_names: ['Movies', 'TV Shows', 'Anime']

# minimum age (days) for NFO/poster/art not to be replaced
# i.e setting 15 means any NFO/poster/art file older than 15 days will not be replaced
# !!!!!!! set lower than how often you plan to run the script !!!!!!!
days_difference: 4

# true/false choose what to export
# !!!!!!! do not wrap in quotes !!!!!!!
export_nfo: true
export_poster: false
export_fanart: false

# change/add path mapping if plex path is different from local (script) path
# !!!!!!! OMMIT THE LAST SLASH "/" !!!!!!!!
path_mapping: [
    {
        'plex': '/data_media',
        'local': '/volume1/data/media'
    },
    {
        'plex': '/usb2',
        'local': '/volumeUSB2/usbshare/data'
    }
]

################################ NFO options ################################

# important
# change only if you know you don't want these metadata
title: true
agent_id: true # will export all available metadata agent ids
tagline: true
plot: true
year: true

# optionals
studio: false
mpaa: false
criticrating: false
customrating: false
runtime: false
releasedate: false
genre: false
country: false
ratings: false
directors: false
writers: false
roles: false
# producers: false # there's no equivalent in jellyfin metadata
